"""add descripcion to categorias

Revision ID: b952fa6c51b9
Revises: ce5d743a3cd5
Create Date: 2026-03-22 03:28:14.347766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b952fa6c51b9'
down_revision: Union[str, Sequence[str], None] = 'ce5d743a3cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos', sa.Column('id_movimiento', sa.Integer(), nullable=False))
    op.drop_column('movimientos', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimientos', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('movimientos', 'id_movimiento')
    # ### end Alembic commands ###
