"""add descripcion to categorias

Revision ID: ce5d743a3cd5
Revises: 1fe09c8e9003
Create Date: 2026-03-22 02:07:12.668551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce5d743a3cd5'
down_revision: Union[str, Sequence[str], None] = '1fe09c8e9003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('descripcion', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorias', 'descripcion')
    # ### end Alembic commands ###
